
<CFMAIL 
TO="sdari@firsttitleservices.com,astone@fusionproductions.com,spape@firsttitleservices.com"
FROM="sdari@firsttitleservices.com" Subject="Import file for an order"
TIMEOUT="600"
	>
				
This is a test generated by code running directly
from the same server as the web site.
				
</CFMAIL>



A message should appear in your mailbox.

