<html>
<head>
<title>Title Company,Title Insurance Company,Title and Escrow,Title Companies</title>
<meta name="description" content="First Title Services: For exceptional Title Insurance, Title and Escrow Services, Title Insurance Company, Title Companies visit firsttitleservices.com." />
<meta name="keywords" content="Title Company, Title Insurance Company, Title and Escrow, Title Companies" />
<link rel="canonical" href="https://www.firsttitleservices.com">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="google-site-verification" content="bqKVm9OHeVBWNNH3eXdyqkVAWIEA5TD3pIMleshYrfk" />
<SCRIPT language=JavaScript>
<!--

//  Script generated by Search Maker Pro:

a=new Array();a[1]=new Array("main.cfm","<cfoutput>#session.site.long_name#</cfoutput>","","LOGO  Entire Site About FT Products Vendors Careers                                  Fast-Track Title Process INSTANT AUTO-HUD - Click above to view INSTANT AUTO-HUD - Seconds After You Place Your Order. AUTO ENDORSEMENT -  No More Waiting for Endorsements - IT'S INSTANTANEOUS - Click above to Find Out How Coverage Areas - We Cover Nearly the ENTIRE United States - Click above for Coverage Insurance Claculator - Borrower Needs Title Insurance Fees? - Click above for INSTANTANEOUS FEES Tailored for Your Deal WELCOME TO <cfoutput>#session.site.short_name#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput> is a full service company dedicated to providing exceptional title insurance, real estate closing and related services to lenders, brokers and purchasers around the country. <cfoutput>#session.site.short_name#</cfoutput> is licensed to write title insurance in thirty-seven states for your residential or commercial real estate transactions. <cfoutput>#session.site.short_name#</cfoutput> performs non-title insurance transactions, appraisals and settlement services in all fifty states. <cfoutput>#session.site.short_name#</cfoutput> provides a centralized single point of contact designed to streamline the processing and tracking of real estate transactions nationwide. We at <cfoutput>#session.site.short_name#</cfoutput> are dedicated to our goal of ensuring that your real estate transaction proceeds flawlessly from opening to closing. We accomplish this by harmonizing our technology-intensive, comprehensive business processing solutions with traditional, time tested methods in order to meet diverse and ever changing client and company requirements. <cfoutput>#session.site.short_name#</cfoutput> believes that service is the single most important element of the vendor management industry. We are dedicated to providing your company with the highest quality of title and other services; and conducting our business for your company in a pro-active manner that exhibits the greatest standards of integrity, professionalism, proficiency, courtesy and dedication. EXPLORE OUR WEB-BASED TRANSACTION SYSTEM Order title, closing, appraisal credit online Monitor order status, view, print and upload documents online AUTO-HUD - Title fees generated seconds after order ENDORSEMENT EXPRESS - Endorsements at your fingertips SIGN UP AS NEW CLIENT TODAY BY CLICKING HERE Technology Solutions - Our technology integreates the speed and use of the internet to deliver data secure and instantenously Personal Solutions - Our staff is trained to offer sincere, personalized service to your staff and borrowers. Service You Can Trust -  Our solutions are delivered from one centralized location, enabling us to maintain maximum control and provide superior service. Home | Terms of Use | Privacy Policy  © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput> ");a[2]=new Array("login.cfm","Login","","LOGO Customer Login Vendor 3rd Party Login Admin Login New Customer Signup New Vendor Signup CUSTOMER LOGIN Welcome to the gateway to <cfoutput>#session.site.short_name#</cfoutput>'s automated, web-based, ordering and tracking system. To login please type your username and password below. Having trouble logging in? Click on one of the links below the login for help. Username:  Password:             Forgot your password? Click here Don&#8217;t have a username and password? Click   Home | Terms of Use | Privacy Policy © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput> ");a[3]=new Array("company.cfm","Company","","LOGO Letter from President Mission Statement The Process <cfoutput>#session.site.long_name#</cfoutput> is a full service company dedicated to providing exceptional title insurance, real estate closing and related services to lenders, brokers and purchasers around the country. <cfoutput>#session.site.short_name#</cfoutput> is licensed to write title insurance in thirty-seven states for your residential or commercial real estate transactions. <cfoutput>#session.site.short_name#</cfoutput> performs non-title insurance transactions, appraisals and settlement services in all fifty states. <cfoutput>#session.site.short_name#</cfoutput> provides a centralized single point of contact designed to streamline the processing and tracking of real estate transactions nationwide. We at <cfoutput>#session.site.short_name#</cfoutput> are dedicated to our goal of ensuring that your real estate transaction proceeds flawlessly from opening to closing. We accomplish this by harmonizing our technology-intensive, comprehensive business processing solutions with traditional, time tested methods in order to meet diverse and ever changing client and company requirements. <cfoutput>#session.site.short_name#</cfoutput> understands that service is the single most important element of our industry. We are dedicated to providing your company with the highest quality of real estate information and other services; and conducting our business for your company in a pro-active manner that exhibits the greatest standards of integrity, professionalism, proficiency, courtesy and dedication.  Home | Terms of Use | Privacy Policy © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput>");a[4]=new Array("services.cfm","Product and Services","","LOGO Title Insurance Programs Title Search Products Loan Closing Services Appraisal Management Credit Reporting Products Flood Products Affilated Opportunities Technology    Home | Terms of Use | Privacy Policy © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput>");a[5]=new Array("vendor.cfm","Vendors","","LOGO BECOME A VENDOR Abstractor/Title Info Attorney Closing Agent Title Closing Agent Notary Closing Agent Appraiser Flood Vendor Credit Vendor AVM Vendor <cfoutput>#session.site.short_name#</cfoutput> is one of the most rapidly growing Title Services companies in America. It is a full service title insurance agency dedicated to providing exceptional title insurance and real estate closing services to lenders, brokers, banking institutions, realtors and purchasers nationwide. <cfoutput>#session.site.short_name#</cfoutput> prides itself on its allegiances with the top mortgage lending institutions in the country. However, these allegiances would not be possible without quality vendor relationships. Vendors are rewarded for superior service and expedient turn times. <cfoutput>#session.site.short_name#</cfoutput> makes it easy for our vendors to provide services and receive compensation therefore, through the use of our state of the art, user friendly technology, and helpful and friendly staff. We are constantly seeking vendors who take pride in their work, provide superior service, and wish to be a part of a team of top quality vendors in all facets of the title industry. By choosing to work with <cfoutput>#session.site.short_name#</cfoutput>, you will enjoy: Timely Payment Exclusive Territories E-Mail Ordering and Reporting Professional and Courteous Treatment Preferred Status for Superior Service - More Business One Click Status Reports If you wish to be part of our team, click on one of the vendor selection areas on the left side of the menu to learn how to become a <cfoutput>#session.site.short_name#</cfoutput> vendor.  Home | Terms of Use | Privacy Policy © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput>");a[6]=new Array("employment.cfm","Careers","","LOGO Life At <cfoutput>#session.site.short_name#</cfoutput> General Employment Employment Application <cfoutput>#session.site.short_name#</cfoutput> is constantly looking for experienced people and enterprises to help service the growing mortgage lending industry. If you or your company would be interested in working with us, please fill out the form below, or feel free to fill out an employment application.  General Employment Inquiry  Area of Interest:  Sales and Marketing Marketing Support Customer Service Representative Accounting and Financial Information Systems Data Entry General Clerical Loan Closer Title Abstractor Title Examiner Appraiser Appraiser Coordinator Closing Coordinator Vendor Coordinator Name:  Are you an:  Independent Contractor Employee E-mail Address:  Phone Number:  Street Address:  City:  State:  Zip Code:  Comments:   Home | Terms of Use | Privacy Policy © 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput>");var b=0;var c=1;var d=2;var e=3;var f=4;var g=5;var h=6;var i=7;var j=8;var k;var l;var m;var n; var yt ; var H=true;var I=1;var K=2;var J=3;var L=4;var T=false;var U=true;var hj=""; function SMPSetFocus() { document.formSearch.txtSearch.focus(); }
function p(q) {if ((q>="a" && q<="z") || (q=="&") ||(q>="A" && q<="Z") || (q>="0" && q <="9")) { return true; } else { return false; } }function r( s, t, u ) {var v=a[s][t].toUpperCase();var w, x, y; var z=0;a[s][g]=0;w=v.indexOf( u );while (w >= 0){ z = z + w + 1;if(( m== -2 ) || ( m== -5 )) { x = false; } else { if (w == 0) { x=false; } else { x=p(v.charAt(w-1)); }  } if(( m == -3 ) || ( m == -5 )) { y = false; } else { if ( v.length - w == u.length) { y = false; } else { y = p(v.charAt(w + u.length)); }  } if (!x && !y) { a[s][j+a[s][g]] = z - 1;a[s][g] ++; } v = v.substring(w+1,v.length);while( p(v.charAt(0)) && v.length > 0 ) { v = v.substring( 1, v.length ) ;z ++; } w = v.indexOf(u); } } function A(s, u) { var t=-1, B; a[s][f]=-1;while( ++t <= e && a[s][f]==-1 ) { B = t==0 ? c : (t==1 ? d : (t==2 ? b : e));r( s, B, u );if ( a[s][g] > 0 ) { a[s][f] = B; } } } function C() { var s, t, D, E;for( s=1; s<a.length; s++ ) { a[s][i] = s; } if( H ) {for( s=1; s<a.length; s++ ) { if( a[s][f] == c ) { a[s][h] = (4-I) * 15000; } else if( a[s][f] == d ) { a[s][h] = (4-K) * 15000; } else if( a[s][f] == b ) { a[s][h] = (4-J) * 15000; } else { a[s][h] = (4-L) * 15000 + a[s][g]; } } for( s=2; s<a.length; s++ ) { D = a[s][h]; E = a[s][i];for( t=s; t>1 && D > a[t-1][h]; t--) { a[t][h] = a[t-1][h];a[t][i] = a[t-1][i]; }a[t][h] = D;a[t][i] = E; } } } function F(s) { var G = a[s][g]==1 ? "" : "es";k += ""; k += "<font color=gray>"; if( a[s][f]==c ) { k += " - matched title"; } else { if( a[s][f]==d ) {k += " - matched description"; } else { if( a[s][f]==b ) { k += " - matched URL"; } else { k += " - " + a[s][g] + " match" + G + "";  } } } k += "</font>"; k += ""; } function M(s, N) { var O;var P;var Q = false; var R=a[s][j + N - 1]; O = R<35 ? O=0 : O=R-35;P = (R+35 > a[s][e].length) ? P=a[s][e].length : P=R+35;while ((O>=0) && !Q) { if(p(a[s][e].charAt(O))) { O--; } else { Q=true; } } O++;Q=false;while ((P > R) && !Q) { if(p(a[s][e].charAt(P))) { P--; } else { Q=true; } } k += "<BR>\".. "+a[s][e].substring(O,R); k += "<B>" + a[s][e].substring(R , R + l.length ) +"</B>";k += a[s][e].substring(R + l.length ,P) + " ..\""; } function S( s ) { if( T==false ) { var t=1; while ( (t < 4) && (t<=a[s][g])) { M( s, t ); t++; } } } function V( v, R ) { k += v.substring( 0, R );k += "<B>" + v.substring( R , R + l.length ) +"</B>";k += v.substring( R + l.length ,v.length ); } function X( s, W ) { k += "<p>" + W +". <big>";k += "<A href=\""+a[s][b]+"\">"+a[s][c]+"</a></big>";if ( a[s][f]==e ) { S(s); } else { k+=""; } if( a[s][f]==d ) { k += "<font color=gray>"; k += "<br>Description: "; k += "</font>"; k += "";V( a[s][d], a[s][j] ); } else { if( a[s][d].length > 0 ) { k += "<font color=gray>"; k += "<br>Description: "; k += "</font>"; k += "" + a[s][d]; } else {  } } k+= "<br>";k += "<font color=#005500>"; if( a[s][f]==b ) { V( a[s][b], a[s][j] ); } else { k += a[s][b]; } k += "</font>"; if( U ) { F( s ); } k += "<br>"; }; function Y() { var W = 0;if (! (n )) { for( var s=1; s<a.length; s++ ) { if( a[a[s][i]][g] > 0 ) { X(a[s][i], ++W); } }  } else { if( m == -4 ) { k += "<P><B>ERROR:</B>&nbsp;The wildcard chararcter (*) must be at the beginning or end of the text."; } }  } function Z() { k += "<html><head><title>Search results for \"" + yt + "\"</title></head><body"; k += ">" ;k+= ("<font face=\"Arial\" size=\"2\">" ); k += "<p>You searched for <b>" + yt +".</b>"; } function fg() { var eh=0;if (!(n)) { for( var s=1; s<a.length; s++ ) { if( a[s][g]>0 ) { eh ++; } }  } if(eh==0) { k += "<P>No pages matched your search.&nbsp;&nbsp;"; } else { var G = eh==1 ? "" : "s"; k += "<P>" + eh + " page" + G + " listed.&nbsp;&nbsp;"; } k += "<A href=\"javascript:self.close();\"><B>Close Window</B></A></P>"; k += hj; k += "</p></body></html>"; } function jf() { var nt = k;iu = open("","Object", "resizable=yes,scrollbars=yes,toolbar=yes,menubar=yes,location=yes,directories=yes,width=590,height=300");if ((navigator.appName.indexOf("Microsoft")!=-1) && (navigator.appVersion.indexOf("3.0")!=-1)) { alert("Click to see results"); } iu.document.open();iu.document.write( nt );iu.document.close(); } function ot( v ) { var qh="";for( var s=0; s<v.length; s++) { if( v.charAt(s)=="<" ) { qh += "&lt;"; } else if( v.charAt(s)==">" ) { qh += "&gt;"; } else if( v.charAt(s)=="\"" ) { qh += "&quot;"; } else { qh += v.charAt(s); } } return( qh ); } function js() { m = l.indexOf("*"); if( m == 0 ) { m = -2; n = false; } else if (m == l.length -1) { m = -3; n = false; } else if (m > 0 ) { m = -4;n = true; } else { n = false; } if ( l.indexOf("*") != l.lastIndexOf("*") ) { if( m == -2 ) { if( l.lastIndexOf("*") == l.length - 1 ) { m = -5; } else { m = -4; n = true; } } }if( ( m == -2 ) || (m == -5 )) { l = l.substring( 1, l.length ); } if( ( m == -3 ) || (m == -5 )) { l = l.substring( 0, l.length - 1 ); } } function startsearch() { var u;l=document.formSearch.txtSearch.value;if (( l.length > 0 )&&( l != "*" )) { k = "";yt = l; l = ot(l);js();u = l.toUpperCase();if ( !(n ) ) { for( var s=1; s<a.length; s++ ) { A( s, u ); } C(); } Z();Y();fg();jf(); } }

//  End of Search Maker Pro script.

//-->
</SCRIPT>


<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</script>
<title><cfoutput>#session.site.long_name#</cfoutput></title>
<style type="text/css">
body
{
    BACKGROUND-COLOR: #284466;
    FONT-FAMILY: Verdana;
    FONT-SIZE: 10px;
    MARGIN: 0px
}
P
{
    COLOR: #66CCFF;
    FONT-FAMILY: Verdana;
    FONT-SIZE: 11px;
    MARGIN-BOTTOM: 7px;
    MARGIN-TOP: 7px
	line-height: 12px;
}
A:link
{
    Color: #66CC00;
    FONT-FAMILY: Verdana;
    FONT-SIZE: 10px;
    FONT-WEIGHT: bold
}
A:visited
{
    Color: #66CC00;
    FONT-FAMILY: Verdana;
    FONT-SIZE: 10px;
    FONT-WEIGHT: bold
}
.HP_STOCK
{
    COLOR: #ffffff;
    FONT-FAMILY: Verdana;
    FONT-SIZE: 12px;
    MARGIN: 0px;
    PADDING-BOTTOM: 0px;
    PADDING-LEFT: 0px;
    PADDING-RIGHT: 0px;
    PADDING-TOP: 0px
}
LI
{
    MARGIN: 5px 0px 0px
}
   </style>
   <STYLE TYPE="text/css">
body {background-attachment:fixed;scrollbar-base-color:#708090}

.menu1 {color:#000000;font:normal bold 11px Arial, Helvetica, sans-serif;text-align:center;font-color:#000000}
.menu1:link    {text-decoration:none;color:#000000;font:normal bold 11px Arial, Helvetica, sans-serif;}
.menu1:visited {text-decoration:none;color:#000000;font:normal bold 11px Arial, Helvetica, sans-serif;}
.menu1:hover   {font:normal bold 11px Arial, Helvetica, sans-serif;text-decoration:none;color:#FFFFFF}

.menu2 {color:#FFFFFF;font:normal bold 13px Arial, Helvetica, sans-serif;text-align:center;font-color:#FFFFFF}
.menu2:link    {text-decoration:none;color:#000000}
.menu2:visited {text-decoration:none;color:#000000}
.menu2:hover   {font:normal bold 14px Arial, Helvetica, sans-serif;text-decoration:none;color:#FFFFFF}
.menu3 {color:#FFFFFF;font:normal bold 10px Verdana, Arial, Helvetica, sans-serif;text-align:center;font-color:#FFFFFF}
.menu3:link    {text-decoration:none;color:#FFFFFF}
.menu3:visited {text-decoration:none;color:#FFFFFF}
.menu3:hover   {font:normal bold 11px Verdana, Arial, Helvetica, sans-serif;text-decoration:none;color:#FF3300}
.menu4 {color:#FFCC33;font:normal bold 15px Verdana, Arial, Helvetica, sans-serif;text-align:center;font-color:#FFCC33}
.menu4:link    {text-decoration:none;color:#FFCC33}
.menu4:visited {text-decoration:none;color:#FFCC33}
.menu4:hover   {font:normal bold 15px Verdana, Arial, Helvetica, sans-serif;text-decoration:none;color:#FFFF00}

.menu5 {color:#FFFFFF;font:normal bold 11px Verdana, Arial, Helvetica, sans-serif;text-align:center;font-color:#FFFFFF}
.menu5:link    {text-decoration:none;color:#FFFFFF}
.menu5:visited {text-decoration:none;color:#FFFFFF}
.menu5:hover   {font:normal bold 11px Verdana, Arial, Helvetica, sans-serif;text-decoration:none;color:#FFFF00}

</STYLE>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22259646-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'https://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>


<body onLoad = SMPSetFocus() leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#294163">
<table width="780" height="110" border=0 cellpadding=0 cellspacing=0 background="images/banner_black_wout_logo.jpg" valign=top>
  <tr>
    <td rowspan="2" valign="top" width="220"><cfinclude template="logo_swap_include.cfm"></td>
    <td valign="top" align="right">
	<br>
	<FORM name=formSearch action="javascript:startsearch() //">
	    <table align="right" cellpadding="0" cellspacing=0>
          <tr>
            <td align="center" valign="middle"><b><font color="96E102" size="2" face="Verdana, Helvetica, sans-serif">Search</font></b>&nbsp;</td>
            <td align="center" valign="center">
              <input type="text" name="txtSearch" size=20>&nbsp;</td>
            <cfoutput><td align="right" valign="bottom"><input type="image" src="https://#cgi.server_name#/client/images/searchgo2.jpg" border=0 alt="Begin your Web search"></td></cfoutput>
			<td width="30">&nbsp;</td>
		  </tr>
		</table>
  </FORM>
</td>
  </tr>
  <tr>
    <td valign="top" align="center" width="560"><nobr></nobr><br>
      &nbsp;</td>
  </tr>
</table>

	<table cellpadding="1" cellspacing="1" border="0" valign="top" width="780">
		<td width="95" bgcolor="#CCD2D2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>

		  <cfoutput><td valign="middle" align = "center" width="95" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##FECE62'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/loginb.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/loginb.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowlogin.jpg" border=0>&nbsp;LOGIN&nbsp;</nobr></a></td>
          <td valign="middle" align = "center" width="95" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##0066CC'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/company.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/company.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowcompany.jpg" border=0>&nbsp;COMPANY&nbsp;</nobr></a></td>
         <td valign="middle"  align = "center" width="95" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##FF0000'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/services.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/services.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowproducts.jpg" border=0>&nbsp;PRODUCTS&nbsp;</nobr></a></td>
<td width="95" valign="middle"  align = "center" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##00FF66'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/vendor.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/vendor.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowvendor.jpg" border=0>&nbsp;VENDORS&nbsp;</nobr></a></td>
	<td width="95" valign="middle"  align = "center" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##FF9900'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/employment.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/employement.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowcareers.jpg" border=0>&nbsp;CAREERS&nbsp;</nobr></a></td>
	<td width="95" valign="middle"  align = "center" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##669999'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/contact.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/contact.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowcontact.jpg" border=0 valign="middel">&nbsp;CONTACT US&nbsp;</nobr></a></td>
		<td valign="middle" align = "center" width="95" bgcolor="##CCD2D2" nowrap onMouseOver="this.bgColor='##0066CC'" onMouseOut="this.bgColor='##CCD2D2'" onClick="document.location.href='https://#cgi.server_name#/client/newsroom.cfm';return false;"><a class="menu1" href="https://#cgi.server_name#/client/newsroom.cfm"><nobr><img src="https://#cgi.server_name#/client/images/arrowcompany.jpg" border=0>&nbsp;IN THE NEWS</nobr></a></td></cfoutput>
	</tr>
			        	 </table>

<table width="780" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="780" height="120" colspan="9" align="top"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="https://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="780" height="120">
        <param name="movie" value="pape7.swf">
        <param name="quality" value="high">
        <embed src="pape7.swf" quality="high" pluginspage="https://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="780" height="120"></embed></object></td>
  </tr>

  <tr>

   <td  width="480" center valign="top" bgcolor="#000000">

<table width="585" border="0" cellspacing="3" cellpadding="3">
	<tbody>
	<tr>

                      <TD width="550" bgColor="000000"><center><p><B><FONT color="94F905">WELCOME TO <cfoutput>#session.site.short_name#</cfoutput></FONT></B></p></center></TD></TR>

<!---                   <TR>
                      <TD width="550" vAlign=top bgColor="000000"><p align = "justify"><FONT color="#FF5F55" size="3">Please click <a href="../site_message_data.cfm" target="message"><font size=3>HERE</font></a> for a special message regarding recent power outages</font></p></TD></TR>
 --->
<TR>
                      <TD width="550" vAlign=top bgColor="000000"><p align = "justify"><FONT color="66C8FB"><cfoutput>#session.site.long_name#</cfoutput> provides
exceptional title insurance, real estate closing and related services to
lenders, brokers, servicers and asset managers in both the origination and default servicing sectors, nationwide.  <cfoutput>#session.site.short_name#</cfoutput> is
licensed
to write title insurance in forty-one states for your residential or
commercial real estate transactions. <br>
<br>
Our Proprietary web-based technology and customized processing solution, results in a faster, more streamlined process for our clients.</font></p></TD></TR>

<tr>

                      <TD bgColor="000000"><center><p><B><FONT color="WHITE">EXPLORE OUR <I><B>"REAL-TIME"</B></I> TITLE PROCESSING SYSTEM</FONT></p></center></TD></TR>
                    <TR>
</tbody>
</TABLE>

<table width="485" border="0" cellspacing="0" cellpadding="0">
	<tr>

		<td width="280" valign="top">

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle3_header.gif" width="280" height="16" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="15" bgcolor="#512BF7"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="15" height="10" border="0" alt=""></td>

					<td width="90" valign="top" bgcolor="#512BF7"><a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/instantHUD.cfm" target="new"><img border="1" alt="Instant hud-1 and GFE Creator" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/hud1.gif"></a></td>
					<td width="163" valign="top" bgcolor="#512BF7">
							<a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/instantHUD.cfm" target="new"><font class = "menu5" ><strong>INSTANT HUD-1 AND GFE CREATOR</strong></font></a><br><br>
<font color = "white" size = 1>
Click above to view INSTANT HUD-1 Seconds After Ordering. Get ALL Closing Fees specific to your order </font>


									</td>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="10" bgcolor="#000000"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="10" height="10" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle3_footer.gif" width="280" height="25" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle4_header.gif" width="280" height="16" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="15" bgcolor="#055E2B"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="15" height="10" border="0" alt=""></td>

					<td width="90" valign="top" bgcolor="#055E2B"><a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/coverage_areas.cfm" target="ft_states" onClick="window.open('','ft_states','width=780,height=680,status=0,resizable=0,scrollbars=0')"><img border="1" width="60" height="60" alt="Nationwide coverage map" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/images.jpg"></a></td>
					<td width="163" valign="top" bgcolor="#055E2B">

							<a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/coverage_areas.cfm" target="ft_states" onClick="window.open('','ft_states','width=630,height=530,status=0,resizable=0,scrollbars=1,menubar=1')"><font class = "menu5" ><strong>NATIONWIDE COVERAGE</strong></font></a><br><br>
<font color = "white" size = 1>We service you nationwide. Click on the map or the link above for selected product coverage areas<br>
<br>
</font></td>

					</td>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="10" bgcolor="#000000"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="10" height="10" border="0" alt=""></td>
				</tr>
			</table>
			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280" height="25" valign="top"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle4_footer.gif" width="280" height="25" border="0" alt=""></td>
				</tr>
			</table>

		</td>


		<td width="280" valign="top">

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle1_header.gif" width="279" height="16" border="0" alt=""></td>
				</tr>
			</table>
			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="15" bgcolor="#0AB854"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="15" height="10" border="0" alt=""></td>
					<td width="90" valign="top" bgcolor="#0AB854"><a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/endorsement_page.cfm" target = "new"><img border="1" alt="Endorsement Express" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/images2.jpg"></a></td>
					<td width="163" valign="top" bgcolor="#0AB854">
						<a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/endorsement_page.cfm" target = "new"><font class = "menu5"><strong>ENDORSEMENT EXPRESS</strong></font></a><br><br>
<font color = "white" size = 1>No More Waiting for Endorsements - IT'S INSTANTANEOUS! To find out more click above </font>

					</td>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="8" bgcolor="#000000"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="8" height="10" border="0" alt=""></td>
				</tr>
			</table>
			<table width="280" border="0" cellpadding="0" cellspacing="0">



				<tr>
					<td width="280" height="25" valign="top" colspan="5"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle1_footer.gif" width="279" height="25" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle2_header.gif" width="279" height="16" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="15" bgcolor="#1B086E"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="15" height="10" border="0" alt=""></td>
					<td width="90" valign="top" bgcolor="#1B086E"><a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/calculator_page.cfm" target = "new"><img border="1" alt="Nationawide Closing Cost Calculator" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/calculator.jpg"></a></td>
					<td width="163" valign="top" bgcolor="#1B086E">

						<a class = "menu5" href="https://<cfoutput>#cgi.server_name#</cfoutput>/calculator_page.cfm" target = "new"><font class = "menu5"><strong>NATIONWIDE CLOSING COST CALCULATOR</strong></font></a><br><br>
<font color = "white" size = 1>Borrower needs Title, Closing and Recordation costs? Click above for INSTANTANEOUS FEES Tailored for Your Loan<br>
</font>
</td>

					</td>
					<td width="2" bgcolor="#FFFFFF"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="2" height="10" border="0" alt=""></td>
					<td width="9" bgcolor="#000000"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ft_0.gif" width="9" height="10" border="0" alt=""></td>
				</tr>
			</table>

			<table width="280" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="280"><img src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/ftitle2_footer.gif" width="279" height="25" border="0" alt=""></td>
				</tr>
			</table>

		</td>

	</tr>
</table>
<table border=0 width="600"><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="newsroom.cfm"><img src="/client/images/Calyx_bug_black.gif"  alt="Calyx Connected Logo" width="83" height="36" border=0></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<!--- <a href="newsroom.cfm"><img src="/client/images/fisher_logo.jpg" width="127" height="60" border="0"></a> --->

<!--- <script src="https://siteseal.thawte.com/cgi/server/thawte_seal_generator.exe"></script> ---><!--- <br>
<a style="color:#AD0034" target="_new"
   href="https://www.thawte.com/digital-certificates/">
   <span style="font-family:arial; font-size:8px; color:#AD0034">
   ABOUT SSL CERTIFICATES</span>
   </a> --->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="newsroom.cfm"><img  alt="Intergrated in Encompass" src="/client/images/encompass_logo_black.jpg" width="122" height="43" border="0"></a>
</td></tr></table>
</td>
    <td  width="280" valign="top" bgcolor="black">

	<table border="0" cellpadding="3" cellspacing="2" style="BORDER-COLLAPSE: collapse" width="90%">
	<tbody>
<tr>
<td align="left" valign="top"><br>
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/tech.cfm"><img border="1" alt="Technology Solutions" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/connected.gif"></a></p>
</td>
<td align="left" valign="top"><br>
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/tech.cfm"><strong>Technology Solutions</strong></a><br>
Our technology integrates the speed and use of the internet to deliver data secure and instantenously
</td>
</tr>

<tr>
<td align="left" valign="top">
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/process.cfm"><img border="1" alt="Personal Solutions" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/geared.gif"></p>
</td>
<td align="left" valign="top">
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/process.cfm">Personal Solutions</a><br>
Our staff is trained to offer sincere, personalized service to your staff and borrowers.
</p>
</td>
</tr>

<tr>
<td align="left" valign="top">
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/services.cfm"><img border="1" alt="Service You Can Trust" src="https://<cfoutput>#cgi.server_name#</cfoutput>/client/images/quality.gif"></a></p>

</td>
<td align="left" valign="top">
<p><a href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/services.cfm"><strong>Service You Can Trust</strong></a>&#160;<br>
Our solutions are delivered from one centralized location, enabling us to maintain maximum control and provide superior service. <!--- We utilize professionals local to your transactions, enabling us to provide your borrowers with the feeling that are closing "next door". ---> </p>
</td>
</tr>
</tbody>
</table>
</td>
  </tr>
</table>


		<table width="780" border="0" cellpadding="4" cellspacing="0">
<tr>

		<td align="left" bgcolor="#0066CC">
			<font face="Verdana, Arial, Helvetica, sans-serif" color="FFFFFF" size="1"><b><a class="menu3" href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/main.cfm">Home<a> | <a class="menu3" href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/termuse.cfm">Terms of Use<a>  | <a class="menu3" href="https://<cfoutput>#cgi.server_name#</cfoutput>/client/policy.cfm">Privacy Policy<a></b></font></td>

		<td align="right" bgcolor="#0066CC"><font face="Verdana, Arial, Helvetica, sans-serif" color="FFFFFF" size="1"><b>© 2003-<cfoutput>#DatePart('yyyy', Now())#</cfoutput> <cfoutput>#session.site.long_name#</cfoutput></b></font></td>
	</tr>

</table>
<!--- <script language="javascript">
window.open('../site_message_data.cfm','message',
    'height=400,width=500,status=yes,toolbar=no,menubar=no,location=no, scrollbars=no');
</script> --->
</body>
</html>
<cfflush>